### ISSUE TITLE
Develop website

### ISSUE THREAD

**Issue by vovikhangcdv** [codeql-agent-project/codeql-cheatsheet#1]
Landing page with these main features:

## Requirements
- Static website.
- Load data from file json.
- SEO optimization (optional)

## TODO
- [x] Choose languages (see https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/)
- [x] List queries of specific language (show query name)
- [x] Show query details (query name, description, author)
- [x] Have a button `Copy to clipboard`
- [ ] Search query

## References
- https://tmuxcheatsheet.com/
- https://lgtm.com/query

### Goals
- UI:
    - A search form in navigation bar
    - Search result page: return result display element reuse other page
- Backend:
    - Lunr.js generate the database in CI/CD step - after main pq, before deploy to server
    - Test search metric priority: By name → description → code content → author → categories tags
### Timetable
- Continuous 5 Days afternoon (26/12 - 30/12) - From 13:00 to 16:00
- Continuous 5 Days afternoon (2/1 - 6/1) - From 13:00 to 16:00
   - First 3 days - Hours: replicate an lunr.js tutorial [https://victoria.dev/blog/add-search-to-hugo-static-sites-with-lunr/](https://victoria.dev/blog/add-search-to-hugo-static-sites-with-lunr/)
   - Another 2 days - 6 Hours: replicate other tutorial if the above appears to not to be useful
   - Final 5 days - 15 Hours: Implement the feature follow above goals
